# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c49afbc51e8d09284230dc01b8206fb3f4fbd3f0f9ee89d4405ce56bad3da1d58ba3f5c4369611bbf7ae32d663593415d9fe6e89a397939307edfa7bd25c4923
  paypal_host: https://sandbox.paypal.com
  app_host: http://4a130d15.ngrok.com/

test:
  secret_key_base: 0f91670e6d318ec9078a67fc6a0e78499fd24306833ef91c9af2f45d552645cb5d30dce4ce09e9e84205e31000be41403b9b79c81dabdc9060d101cf230ebf33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: https://camacco.herokuapp.com
